package bootkube

import (
	"os"
	"path/filepath"

	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/asset/templates/common"
)

const (
	openshiftMachineConfigOperatorFileName = "04-openshift-machine-config-operator.yaml"
)

var _ asset.Asset = (*OpenshiftMachineConfigOperator)(nil)

// OpenshiftMachineConfigOperator is the constant to represent contents of Openshift_MachineConfigOperator.yaml file
type OpenshiftMachineConfigOperator struct {
	file *asset.File
}

// Dependencies returns all of the dependencies directly needed by the asset
func (t *OpenshiftMachineConfigOperator) Dependencies() []asset.Asset {
	return []asset.Asset{}
}

// Name returns the human-friendly name of the asset.
func (t *OpenshiftMachineConfigOperator) Name() string {
	return "OpenshiftMachineConfigOperator"
}

// Generate generates the actual files by this asset
func (t *OpenshiftMachineConfigOperator) Generate(parents asset.Parents) error {
	data, err := common.GetBootkubeTemplate(openshiftMachineConfigOperatorFileName)
	if err != nil {
		return err
	}
	t.file = &asset.File{
		Filename: filepath.Join(common.TemplateDir, openshiftMachineConfigOperatorFileName),
		Data:     []byte(data),
	}
	return nil
}

// Files returns the files generated by the asset.
func (t *OpenshiftMachineConfigOperator) Files() []*asset.File {
	return []*asset.File{t.file}
}

// Load returns the asset from disk.
func (t *OpenshiftMachineConfigOperator) Load(f asset.FileFetcher) (bool, error) {
	file, err := f.FetchByName(filepath.Join(common.TemplateDir, openshiftMachineConfigOperatorFileName))
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, err
	}
	t.file = file
	return true, nil
}
