package bootkube

import (
	"os"
	"path/filepath"

	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/asset/templates/common"
)

const (
	openshiftClusterAPINamespaceFileName = "05-openshift-cluster-api-namespace.yaml"
)

var _ asset.Asset = (*OpenshiftClusterAPINamespace)(nil)

// OpenshiftClusterAPINamespace is the constant to represent contents of Openshift_ClusterApiNamespace.yaml file
type OpenshiftClusterAPINamespace struct {
	file *asset.File
}

// Dependencies returns all of the dependencies directly needed by the asset
func (t *OpenshiftClusterAPINamespace) Dependencies() []asset.Asset {
	return []asset.Asset{}
}

// Name returns the human-friendly name of the asset.
func (t *OpenshiftClusterAPINamespace) Name() string {
	return "OpenshiftClusterAPINamespace"
}

// Generate generates the actual files by this asset
func (t *OpenshiftClusterAPINamespace) Generate(parents asset.Parents) error {
	data, err := common.GetBootkubeTemplate(openshiftClusterAPINamespaceFileName)
	if err != nil {
		return err
	}
	t.file = &asset.File{

		Filename: filepath.Join(common.TemplateDir, openshiftClusterAPINamespaceFileName),
		Data:     []byte(data),
	}
	return nil
}

// Files returns the files generated by the asset.
func (t *OpenshiftClusterAPINamespace) Files() []*asset.File {
	return []*asset.File{t.file}
}

// Load returns the asset from disk.
func (t *OpenshiftClusterAPINamespace) Load(f asset.FileFetcher) (bool, error) {
	file, err := f.FetchByName(filepath.Join(common.TemplateDir, openshiftClusterAPINamespaceFileName))
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, err
	}
	t.file = file
	return true, nil
}
