ignored = [
  "github.com/openshift/installer/pkg/terraform/exec/plugins*",
  "golang.org/x/net*"
]

required = [
  "github.com/hashicorp/terraform/helper/acctest",
  "github.com/hashicorp/terraform/helper/customdiff",
  "github.com/hashicorp/terraform/helper/schema",
  "github.com/hashicorp/terraform/helper/resource",
  "github.com/hashicorp/terraform/helper/encryption"
]

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  name = "github.com/hashicorp/logutils"
  version = "1.0.0"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "=0.12.9"

[[constraint]]
  name = "github.com/mitchellh/cli"
  version = "1.0.0"

# Due to dep's inabiltiy to read go modules correclty overrides are required.

[[override]]
  name = "github.com/hashicorp/go-version"
  revision = "v1.1.0"

[[override]]
  name = "github.com/hashicorp/hcl2"
  revision = "0c888d1241f6523caa75fd64dfcf8d3b610c77f9"

[[override]]
  name = "github.com/zclconf/go-cty"
  version = "=1.1.0"

[[override]]
  name = "github.com/Azure/azure-sdk-for-go"
  revision = "v21.3.0"

[[override]]
  name = "github.com/Azure/go-autorest"
  revision = "v10.15.4"

[[override]]
  name = "github.com/gophercloud/gophercloud"
  revision = "bc37892e196848d7d56ba0db974ba1d7d5c43b2a"

[[override]]
  name = "github.com/gophercloud/utils"
  revision = "fbb6ab446f0167dfa4d25b8eb0c0d2f873924516"

[[override]]
  name = "github.com/hashicorp/go-retryablehttp"
  revision = "v0.5.2"

[[override]]
  name = "github.com/hashicorp/go-azure-helpers"
  revision = "166dfd221bb20c95f9db5be961c647a67646831e"

[[override]]
  name = "github.com/hashicorp/go-plugin"
  revision = "a1bc61569a26c0f65865932c0d55743b0567c494"

[[override]]
  name = "github.com/hashicorp/go-getter"
  version = "=1.4.0"

[[override]]
  name = "github.com/hashicorp/go-tfe"
  revision = "v0.3.16"

[[override]]
  name = "github.com/terraform-providers/terraform-provider-openstack"
  revision = "v1.15.0"

[[override]]
  name = "github.com/aws/aws-sdk-go"
  version = "=1.22.0"

[[override]]
  name = "github.com/aliyun/alibaba-cloud-sdk-go"
  revision = "6e358769c32a85804dc3d4e6c8c14875338aa97a"

[[override]]
  name = "github.com/jmespath/go-jmespath"
  revision = "c2b33e8439af944379acbdd9c3a5fe0bc44bd8a5"

[[override]]
  name = "golang.org/x/oauth2"
  revision = "0f29369cfe4552d0e4bcddc57cc75f4d7e672a33"

[[override]]
  name = "github.com/golang/protobuf"
  version = "=1.3.2"

